//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.ProcessOrLaw = new HashSet<ProcessOrLaw>();
            this.Office = new HashSet<Office>();
        }
    
        public int Id { get; set; }
        public int AddressCategoryId { get; set; }
        public int AddressTypeId { get; set; }
        public string AddressTyp { get; set; }
        public string PostalCode { get; set; }
        public string Residence { get; set; }
        public string StreetName { get; set; }
        public string HouseNumber { get; set; }
        public string HouseNumberCharacterAddition { get; set; }
        public string HouseNumberAddition { get; set; }
        public string Postaddress { get; set; }
        public string EmployerContactname { get; set; }
        public string IdcdNraanduiding { get; set; }
        public Nullable<int> Client_Id { get; set; }
    
        public virtual AddressCategory AddressCategory { get; set; }
        public virtual AddressType AddressType { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessOrLaw> ProcessOrLaw { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Office> Office { get; set; }
    }
}
