//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class AosCode
    {
        public int Id { get; set; }
        public int LaunchCodeId { get; set; }
        public int TemplateId { get; set; }
        public string CdClassificatie { get; set; }
    
        public virtual LaunchCode LaunchCode { get; set; }
        public virtual Template Template { get; set; }
    }
}
