//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CbbsResult
    {
        public int Id { get; set; }
        public int TheoretischeVerdienCapaciteitId { get; set; }
        public string Code { get; set; }
        public string JobDescription { get; set; }
        public int Row { get; set; }
        public Nullable<decimal> MediaanUurloon { get; set; }
        public Nullable<decimal> ReductieFactor { get; set; }
        public Nullable<int> NumberOfJobs { get; set; }
    
        public virtual TheoretischeVerdienCapaciteit TheoretischeVerdienCapaciteit { get; set; }
    }
}
