//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CbsIndexIkv
    {
        public int Id { get; set; }
        public int CbsIndexType { get; set; }
        public int InkomstenVerhoudingId { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public decimal Index { get; set; }
        public int IndexBaseYear { get; set; }
    
        public virtual InkomstenVerhouding InkomstenVerhouding { get; set; }
    }
}
