//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CbsIndex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CbsIndex()
        {
            this.HerindexeringMaatman = new HashSet<HerindexeringMaatman>();
        }
    
        public int Id { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public decimal Index { get; set; }
        public int IndexBaseYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HerindexeringMaatman> HerindexeringMaatman { get; set; }
    }
}
