//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Address = new HashSet<Address>();
            this.Case = new HashSet<Case>();
            this.EndUser = new HashSet<EndUser>();
        }
    
        public int Id { get; set; }
        public string Bsn { get; set; }
        public string Voornamen { get; set; }
        public string Voorletters { get; set; }
        public string Voorvoegsel { get; set; }
        public string Achternaam { get; set; }
        public Nullable<System.DateTime> GeboorteDatum { get; set; }
        public string Geslacht { get; set; }
        public string CdAanduidingNaamgebruik { get; set; }
        public string VoorvoegselEchtgenoot { get; set; }
        public string AchternaamEchtgenoot { get; set; }
        public string Woonplaats { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Case> Case { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EndUser> EndUser { get; set; }
    }
}
