//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomTextBlock
    {
        public int Id { get; set; }
        public int EndUserId { get; set; }
        public string Name { get; set; }
        public string CustomUserText { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string InsertUser { get; set; }
        public string UpdateUser { get; set; }
    
        public virtual EndUser EndUser { get; set; }
    }
}
