//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentVariable
    {
        public int DocumentVariableId { get; set; }
        public string DocumentVariableName { get; set; }
        public string DocumentVariableIdFromModus { get; set; }
        public string Title { get; set; }
        public string Mask { get; set; }
        public string ValuehelpName { get; set; }
        public string ValuehelpSystem { get; set; }
        public int ValuehelpType { get; set; }
        public string InputEnabled { get; set; }
        public string DataLink { get; set; }
        public string DataAttribute { get; set; }
        public int InputRequired { get; set; }
        public Nullable<int> BravoDocument_DocumentId { get; set; }
    
        public virtual BravoDocument BravoDocument { get; set; }
    }
}
