//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class HerindexeringMaatman
    {
        public int Id { get; set; }
        public int CbsIndexHuidigId { get; set; }
        public decimal MaatmanUurloonHistory { get; set; }
        public decimal MaatmanUurloonGeherindexeerd { get; set; }
        public decimal UrenomvangMaatmanPerWeek { get; set; }
        public bool IndicatieTussenMaatman { get; set; }
        public Nullable<decimal> BedragTussenMaatman { get; set; }
        public decimal IndexcijferHistory { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual CbsIndex CbsIndex { get; set; }
    }
}
