//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class InkomstenOpgave
    {
        public int Id { get; set; }
        public int InkomstenVerhoudingId { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> AantSvDagen { get; set; }
        public Nullable<int> AantVerloondeUren { get; set; }
        public Nullable<decimal> BedrLoonLbPremieVolksverz { get; set; }
        public Nullable<decimal> BedrLoonSv { get; set; }
        public Nullable<decimal> BedrVakantietoeslag { get; set; }
        public Nullable<decimal> BedrOpgebouwdRechtVakToeslag { get; set; }
        public Nullable<decimal> BedrExtraPeriodeSalaris { get; set; }
        public Nullable<decimal> BedrOpgbRechtExtraPrdSalaris { get; set; }
        public Nullable<decimal> BedrVerstrekteAanvUitkWnverz { get; set; }
        public Nullable<decimal> BedrPremieUfo { get; set; }
        public int Tijdvak { get; set; }
        public bool Maatgevend { get; set; }
        public Nullable<int> WerkUren { get; set; }
        public string Toelichting { get; set; }
    
        public virtual InkomstenVerhouding InkomstenVerhouding { get; set; }
    }
}
