//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaatManResultaat
    {
        public int Id { get; set; }
        public int InkomstenVerhoudingenSetId { get; set; }
        public decimal SamengesteldMaatManLoonPerUur { get; set; }
        public decimal SamengesteldMaatManOmvangPerWeek { get; set; }
    
        public virtual InkomstenVerhoudingenSet InkomstenVerhoudingenSet { get; set; }
    }
}
