//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaatManLoon
    {
        public int MaatManLoonId { get; set; }
        public decimal BedragTussenMaatManLoon { get; set; }
        public decimal OngeindexeerdMaatManLoonPerUur { get; set; }
        public decimal MaatManLoonPerUur { get; set; }
        public decimal MaatManOmvangPerWeek { get; set; }
        public int AantSvDagenRefertePeriode { get; set; }
        public int AantUrenRefertePeriode { get; set; }
        public decimal BedrLoonSvRefertePeriode { get; set; }
        public decimal BedrVakantietoeslagRefertePeriode { get; set; }
        public decimal BedrOpgebouwdRechtVakToeslagRefertePeriode { get; set; }
        public decimal BedrExtraPeriodeSalarisRefertePeriode { get; set; }
        public decimal BedrOpgbRechtExtraPrdSalarisRefertePeriode { get; set; }
        public decimal CorrectieFactorOnregelmatigArbeidsPatroon { get; set; }
    
        public virtual InkomstenVerhouding InkomstenVerhouding { get; set; }
    }
}
