//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedischeBeperking
    {
        public int Id { get; set; }
        public Nullable<decimal> UrenomvangPerWeek { get; set; }
        public Nullable<decimal> UrenomvangPerDag { get; set; }
    
        public virtual Case Case { get; set; }
    }
}
