//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BravoContext : DbContext
    {
        public BravoContext()
            : base("name=BravoContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<AddressCategory> AddressCategory { get; set; }
        public virtual DbSet<AddressType> AddressType { get; set; }
        public virtual DbSet<AosCode> AosCode { get; set; }
        public virtual DbSet<ArbeidsVerleden> ArbeidsVerleden { get; set; }
        public virtual DbSet<AuthorizedAction> AuthorizedAction { get; set; }
        public virtual DbSet<BravoDocument> BravoDocument { get; set; }
        public virtual DbSet<Case> Case { get; set; }
        public virtual DbSet<CbbsResult> CbbsResult { get; set; }
        public virtual DbSet<CbsIndex> CbsIndex { get; set; }
        public virtual DbSet<CbsIndexIkv> CbsIndexIkv { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<CustomTextBlock> CustomTextBlock { get; set; }
        public virtual DbSet<DiagnoseCode> DiagnoseCode { get; set; }
        public virtual DbSet<DiagnoseCodeSection> DiagnoseCodeSection { get; set; }
        public virtual DbSet<DocumentHistory> DocumentHistory { get; set; }
        public virtual DbSet<DocumentType> DocumentType { get; set; }
        public virtual DbSet<DocumentVariable> DocumentVariable { get; set; }
        public virtual DbSet<EndUser> EndUser { get; set; }
        public virtual DbSet<GegevensPeriode> GegevensPeriode { get; set; }
        public virtual DbSet<HerindexeringMaatman> HerindexeringMaatman { get; set; }
        public virtual DbSet<InkomstenOpgave> InkomstenOpgave { get; set; }
        public virtual DbSet<InkomstenVerhouding> InkomstenVerhouding { get; set; }
        public virtual DbSet<InkomstenVerhoudingenSet> InkomstenVerhoudingenSet { get; set; }
        public virtual DbSet<LaunchCode> LaunchCode { get; set; }
        public virtual DbSet<MaatManLoon> MaatManLoon { get; set; }
        public virtual DbSet<MaatManResultaat> MaatManResultaat { get; set; }
        public virtual DbSet<MedischeBeperking> MedischeBeperking { get; set; }
        public virtual DbSet<MqMessagesEAED> MqMessagesEAED { get; set; }
        public virtual DbSet<MqMessagesMisDb> MqMessagesMisDb { get; set; }
        public virtual DbSet<Office> Office { get; set; }
        public virtual DbSet<OorzaakCode> OorzaakCode { get; set; }
        public virtual DbSet<Popup> Popup { get; set; }
        public virtual DbSet<PopupText> PopupText { get; set; }
        public virtual DbSet<PopupTree> PopupTree { get; set; }
        public virtual DbSet<PraktischeVerdienCapaciteitResultaat> PraktischeVerdienCapaciteitResultaat { get; set; }
        public virtual DbSet<PrivateAutocorrectList> PrivateAutocorrectList { get; set; }
        public virtual DbSet<ProcessOrLaw> ProcessOrLaw { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleAuthorizedActions> RoleAuthorizedActions { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Template> Template { get; set; }
        public virtual DbSet<TextBlock> TextBlock { get; set; }
        public virtual DbSet<TheoretischeVerdienCapaciteit> TheoretischeVerdienCapaciteit { get; set; }
        public virtual DbSet<UserSetting> UserSetting { get; set; }
        public virtual DbSet<WerkgeverGegevens> WerkgeverGegevens { get; set; }
    }
}
