//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Popup
    {
        public int Id { get; set; }
        public int DocumentId { get; set; }
        public string BundleName { get; set; }
        public string PdcProcessId { get; set; }
        public string XmlStructure { get; set; }
        public string HtmlDocument { get; set; }
        public string ReferenceToRootDoc { get; set; }
    
        public virtual BravoDocument BravoDocument { get; set; }
    }
}
