//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextBlock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TextBlock()
        {
            this.TextBlock1 = new HashSet<TextBlock>();
        }
    
        public int TextBlockId { get; set; }
        public string TextBlockName { get; set; }
        public int State { get; set; }
        public int Enabled { get; set; }
        public int ChildCount { get; set; }
        public short IsExternalDocument { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Reference { get; set; }
        public Nullable<int> TextBlock_TextBlockId { get; set; }
        public Nullable<int> BravoDocument_DocumentId { get; set; }
    
        public virtual BravoDocument BravoDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TextBlock> TextBlock1 { get; set; }
        public virtual TextBlock TextBlock2 { get; set; }
    }
}
