//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheoretischeVerdienCapaciteit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TheoretischeVerdienCapaciteit()
        {
            this.CbbsResult = new HashSet<CbbsResult>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> MediaanUurloon { get; set; }
        public Nullable<decimal> UrenomvangResterendeVerdienCapaciteit { get; set; }
        public Nullable<decimal> ReductieFactor { get; set; }
        public Nullable<decimal> PercentageReductieMedischeUrenBeperking { get; set; }
        public Nullable<decimal> ResterendeVerdienCapaciteitPerUur { get; set; }
        public Nullable<decimal> ResterendeVerdienCapaciteitPerMaand { get; set; }
        public Nullable<decimal> ArbeidsOngeschiktheidsPercentage { get; set; }
        public Nullable<decimal> PercentageResterendeVerdienCapaciteit { get; set; }
    
        public virtual Case Case { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CbbsResult> CbbsResult { get; set; }
    }
}
