//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public int Id { get; set; }
        public int EndUserId { get; set; }
        public string Keyword { get; set; }
        public string Value { get; set; }
    
        public virtual EndUser EndUser { get; set; }
    }
}
