// <auto-generated />
namespace Inficom.Mvc5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update01));
        
        string IMigrationMetadata.Id
        {
            get { return "201902260857069_update01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
